In [ ]:
import numpy as np

In [ ]:
# 1.Create a numpy array of size 2 x 2
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

In [ ]:
# 2.Create a random numpy array of size 3 x 4
a = np.random.rand(3, 4)
print(a)

In [ ]:
# 3.Create a numpy array of ones and a numpy array of zeroes
a = np.ones((2,5), dtype=int)
b = np.zeros(10, dtype=int)

print(a)
print(b)

In [8]:
# 4.Create a random numpy array of size 6x3 and transpose it
a = np.random.rand(6, 3)
a = np.transpose(a)
print(a)

[[0.83349058 0.15469561 0.70723    0.17356482 0.98983201 0.91088076]
 [0.99406042 0.78780785 0.70056505 0.33855275 0.81245783 0.97896647]
 [0.97877065 0.34285871 0.50041518 0.26531165 0.65467128 0.25837844]]


In [ ]:
# 5.Create two random numpy array of size n x p and p x m and then compute the dot product
a = np.random.rand(3, 4)
b = np.random.rand(4, 5)
print(a.dot(b))